name: fixed_nucleifluorescence
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-image
  - scipy
  - jupyterlab
  - ipykernel
  - napari
  - seaborn
  - h5py
  - pyyaml
  - pypaml
  - scikit-learn

  - pip:
      - ruff
      - black
