raw_data_dir: "/mnt/md1/elysse/for r21/meki/nuclei"
segmentation_dir_raw: "/mnt/md1/elysse/for r21/meki/nuclei/segmentation"
segmentation_dir: "/mnt/md1/elysse/for r21/meki/nuclei/segmentation/cleaned"
output_dir: "/mnt/md1/elysse/for r21/meki/nuclei/analysis"

file_extension: ".tif"

microscopy:
  voxel_size_zyx: [2, 0.208, 0.208]
  channels:
    dapi: 0
