"""
ICM distance (t=30) vs radial position — the correlation, the peripheral-tail
test, and the attrition caveat, in one figure.

Built from the one surviving artifact that carries both variables:
continuous_per_track_table_{version}.csv, output of
pipelines/tracking/36_continuous_multivariate_analysis.py. The intermediate
curated tracks (motion_kinematics_*.csv, volume_track_stats_*.csv) are gone, so
this cannot be regenerated by re-running the pipeline.

Panels
------
A  Correlation across the full range, plus the median-split 2x2 that answers
   "are the most peripheral cells the ones that started furthest from the ICM?"
B  The same tail question at three thresholds (top half / tertile / quartile),
   to show the direction is consistent even though no cut reaches significance.
C  The attrition caveat. late_radial requires a track to survive to t>=80;
   23 of the 66 tracks with an ICM distance do not. Those 23 are themselves
   ICM-proximal (median 57.0 vs 70.5 um, Mann-Whitney p=0.04), so the analysed
   sample is depleted of exactly the cells that populate the low end of the
   x-axis in panels A and B. That both attenuates rho and removes the cells
   whose radial fate would settle the 2x2.

Also emits a second, descriptive-only figure (icm_vs_peripheral_trend_*.png):
the same data as panel A with no test statistics at all — scatter plus binned
medians — for preliminary use where a p-value on one embryo would overstate
what 43 tracks can support.

Single embryo, n=43 — preliminary. Run with:
  conda run -n napari_env python3 scripts/replot_icm_vs_late_radial.py
  conda run -n napari_env python3 scripts/replot_icm_vs_late_radial.py --csv PATH --out DIR
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import spearmanr, pearsonr, mannwhitneyu, fisher_exact

DEFAULT_CSV = Path('/Volumes/T7 Shield/examples/outgrowth tracks analysis/'
                   'continuous_per_track_table_linked_c62.csv')

C_PERI = '#2a78d6'   # categorical slot 1 — peripheral
C_CENT = '#1baf7a'   # categorical slot 3 — central
C_DROP = '#eb6834'   # categorical slot 2 — excluded from the analysis
INK, INK2, MUTED = '#0b0b0b', '#52514e', '#8a8984'
GRID, SURF = '#dddcd8', '#fcfcfb'

parser = argparse.ArgumentParser()
parser.add_argument('--csv', type=Path, default=DEFAULT_CSV)
parser.add_argument('--out', type=Path, default=None)
args = parser.parse_args()

out_dir = args.out or args.csv.parent
version = args.csv.stem.replace('continuous_per_track_table_', '')

df = pd.read_csv(args.csv)
scored  = df[df['icm_dist_um'].notna()]
d       = scored[scored['late_radial'].notna()].copy()
dropped = scored[scored['late_radial'].isna()]

rho, p_rho = spearmanr(d['icm_dist_um'], d['late_radial'])
r,   p_r   = pearsonr(d['icm_dist_um'], d['late_radial'])
_,   p_att = mannwhitneyu(d['icm_dist_um'], dropped['icm_dist_um'])

m_rad, m_icm = d['late_radial'].median(), d['icm_dist_um'].median()
peri, far = d['late_radial'] >= m_rad, d['icm_dist_um'] >= m_icm
n_pf, n_pn = (peri & far).sum(), (peri & ~far).sum()
n_cf, n_cn = (~peri & far).sum(), (~peri & ~far).sum()
# odds of "far from ICM" among peripheral vs among central
odds_ratio = (n_pf / n_pn) / (n_cf / n_cn)
_, p_fish = fisher_exact([[n_pf, n_pn], [n_cf, n_cn]])

plt.rcParams.update({'font.size': 10, 'axes.edgecolor': INK2,
                     'axes.labelcolor': INK, 'text.color': INK,
                     'xtick.color': INK2, 'ytick.color': INK2})

fig, (axA, axB, axC) = plt.subplots(
    1, 3, figsize=(15.5, 5.2), gridspec_kw={'width_ratios': [1.45, 1.0, 0.85]})
fig.patch.set_facecolor(SURF)

# ── A ─ correlation + median-split quadrants ──────────────────────────────────
axA.grid(True, color=GRID, lw=0.6, zorder=0)
axA.set_axisbelow(True)
axA.axhline(m_rad, color=MUTED, lw=1, ls=':', zorder=1)
axA.axvline(m_icm, color=MUTED, lw=1, ls=':', zorder=1)

for mask, col in [(peri, C_PERI), (~peri, C_CENT)]:
    axA.scatter(d.loc[mask, 'icm_dist_um'], d.loc[mask, 'late_radial'],
                s=62, c=col, edgecolors=SURF, linewidths=1.5, alpha=0.9, zorder=3)

xs = np.array([d['icm_dist_um'].min(), d['icm_dist_um'].max()])
slope, icept = np.polyfit(d['icm_dist_um'], d['late_radial'], 1)
axA.plot(xs, slope * xs + icept, color=INK2, lw=2, ls='--', zorder=2)

xlo, xhi = axA.get_xlim(); ylo, yhi = axA.get_ylim()
yhi += 4                      # headroom so the stats box clears the data
axA.set_ylim(ylo, yhi)
# quadrant counts sit at each quadrant's centre, behind the marks, so they
# never collide with the corner annotation boxes
for x, y, n in [((m_icm + xhi) / 2, (m_rad + yhi) / 2, n_pf),
                ((xlo + m_icm) / 2, (m_rad + yhi) / 2, n_pn),
                ((m_icm + xhi) / 2, (ylo + m_rad) / 2, n_cf),
                ((xlo + m_icm) / 2, (ylo + m_rad) / 2, n_cn)]:
    axA.text(x, y, f'n={n}', ha='center', va='center', fontsize=15,
             color=MUTED, alpha=0.45, zorder=1)

axA.text(0.03, 0.965,
         f'Spearman ρ={rho:.2f}  p={p_rho:.2f}\nPearson  r={r:.2f}  p={p_r:.2f}',
         transform=axA.transAxes, va='top', ha='left', fontsize=9, color=INK2,
         bbox=dict(boxstyle='round,pad=0.45', fc=SURF, ec=GRID))
# the 2x2 summary lives below the axes — inside, it fought the corner marks
axA.text(0.5, -0.235,
         f'peripheral & far from ICM: {n_pf}/{n_pf+n_pn} = {n_pf/(n_pf+n_pn):.0%}'
         f'   vs   central & far from ICM: {n_cf}/{n_cf+n_cn} = {n_cf/(n_cf+n_cn):.0%}\n'
         f'odds ratio {odds_ratio:.1f}×,  Fisher p={p_fish:.2f}',
         transform=axA.transAxes, va='top', ha='center', fontsize=9, color=INK2,
         bbox=dict(boxstyle='round,pad=0.45', fc=SURF, ec=GRID))

axA.set_xlabel('ICM distance at t=30 (µm)')
axA.set_ylabel('Mean radial distance from embryo centre, t≥80 (µm)')
axA.set_title('A · No correlation across the full range,\n'
              'but the peripheral quadrant leans far-from-ICM',
              fontsize=11, color=INK, loc='left')
axA.text(0.5, 1.005, '', transform=axA.transAxes)
axA.annotate('peripheral', xy=(0.012, m_rad), xycoords=('axes fraction', 'data'),
             xytext=(4, 6), textcoords='offset points', fontsize=9, color=C_PERI)
axA.annotate('central', xy=(0.012, m_rad), xycoords=('axes fraction', 'data'),
             xytext=(4, -14), textcoords='offset points', fontsize=9, color=C_CENT)

# ── B ─ the tail test at three thresholds ─────────────────────────────────────
axB.grid(True, axis='y', color=GRID, lw=0.6, zorder=0)
axB.set_axisbelow(True)
cuts = [('Top half\n(n=22 vs 21)', 0.5), ('Top tertile\n(n=15 vs 28)', 2/3),
        ('Top quartile\n(n=11 vs 32)', 0.75)]
for i, (lab, q) in enumerate(cuts):
    thr = d['late_radial'].quantile(q)
    grp = {'peri': d[d['late_radial'] >= thr], 'cent': d[d['late_radial'] < thr]}
    _, p_one = mannwhitneyu(grp['peri']['icm_dist_um'], grp['cent']['icm_dist_um'],
                            alternative='greater')
    meds = {}
    for j, (key, col) in enumerate([('peri', C_PERI), ('cent', C_CENT)]):
        v = grp[key]['icm_dist_um']
        x = i + (-0.16 if j == 0 else 0.16)
        meds[key] = v.median()
        axB.vlines(x, v.quantile(.25), v.quantile(.75), color=col, lw=3,
                   alpha=0.45, zorder=2)
        axB.scatter([x], [v.median()], s=110, c=col, edgecolors=SURF,
                    linewidths=1.8, zorder=4)
    axB.plot([i - 0.16, i + 0.16], [meds['peri'], meds['cent']],
             color=MUTED, lw=1, ls='-', zorder=3)
    axB.text(i, 96, f'p={p_one:.2f}', ha='center', fontsize=9.5, color=INK2)

axB.set_xticks(range(len(cuts)))
axB.set_xticklabels([c[0] for c in cuts], fontsize=9)
axB.set_xlim(-0.55, len(cuts) - 0.45)
axB.set_ylim(35, 101)
axB.set_ylabel('ICM distance at t=30 (µm)\nmedian ± IQR')
axB.set_title('B · Same direction at every cut,\nnone of them significant',
              fontsize=11, color=INK, loc='left')
axB.scatter([], [], s=90, c=C_PERI, label='most peripheral')
axB.scatter([], [], s=90, c=C_CENT, label='all others')
axB.legend(frameon=False, loc='lower left', fontsize=9)

# ── C ─ attrition ─────────────────────────────────────────────────────────────
axC.grid(True, axis='x', color=GRID, lw=0.6, zorder=0)
axC.set_axisbelow(True)
rng = np.random.default_rng(0)
for y, grp, col, lab in [
        (1, d,       MUTED,  f'analysed\n(n={len(d)})'),
        (0, dropped, C_DROP, f'track ends\nbefore t≥80\n(n={len(dropped)})')]:
    axC.scatter(grp['icm_dist_um'], y + rng.uniform(-0.15, 0.15, len(grp)),
                s=46, c=col, edgecolors=SURF, linewidths=1.3, alpha=0.9, zorder=3)
    axC.plot([grp['icm_dist_um'].median()] * 2, [y - 0.28, y + 0.28],
             color=INK, lw=2.5, zorder=4)
    axC.text(-0.04, y, lab, transform=axC.get_yaxis_transform(),
             va='center', ha='right', fontsize=9, color=INK2)

axC.set_ylim(-0.7, 1.7)
axC.set_yticks([])
axC.set_xlabel('ICM distance at t=30 (µm)')
axC.set_title(f'C · The cells panels A–B are missing\n'
              f'are the ICM-proximal ones  (p={p_att:.2f})',
              fontsize=11, color=INK, loc='left')
axC.text(0.5, -0.22,
         f'median {dropped["icm_dist_um"].median():.1f} vs {d["icm_dist_um"].median():.1f} µm\n'
         'Their radial fate is unknown, and it is\nexactly what would settle panel A.',
         transform=axC.transAxes, ha='center', va='top', fontsize=9, color=INK2)
for side in ('left', 'right', 'top'):
    axC.spines[side].set_visible(False)

fig.suptitle('Do cells that start furthest from the ICM end up most peripheral?   '
             f'· dataset001 control_2 · {version}', fontsize=13, y=1.03)
fig.text(0.5, -0.02,
         'PRELIMINARY — one embryo, n=43 tracks. Source: continuous_per_track_table (script 36); '
         'the curated tracks this was derived from no longer exist.\n'
         'An earlier figure (icm_vs_final_position) reported ρ=0.41, p=0.001 at n=66 by taking each track\'s '
         'LAST frame as "final radial", pooling tracks that end at different times;\n'
         'the fixed t≥80 window used here is the sounder measure but costs 23 tracks, and panel C shows that '
         'loss is not random. Direction is suggestive, significance is not established.',
         ha='center', va='top', fontsize=8.5, color=INK2)

fig.tight_layout()
out_path = out_dir / f'icm_vs_peripheral_summary_{version}.png'
fig.savefig(out_path, dpi=200, bbox_inches='tight', facecolor=SURF)
print(f'Saved: {out_path}')
print(f'  A  n={len(d)}  rho={rho:.3f} p={p_rho:.3g} | r={r:.3f} p={p_r:.3g}')
print(f'     2x2 peripheral&far={n_pf} peripheral&near={n_pn} central&far={n_cf} '
      f'central&near={n_cn}  OR={odds_ratio:.2f} Fisher p={p_fish:.3f}')
print(f'  C  dropped n={len(dropped)}  median {dropped["icm_dist_um"].median():.1f} '
      f'vs {d["icm_dist_um"].median():.1f} um  MWU p={p_att:.3g}')


# ── descriptive-only version of panel A ───────────────────────────────────────
# Panel A with every test statistic stripped out: no rho, no p-value, no odds
# ratio. What stays is descriptive — the scatter, the two median lines, and how
# many cells fall in each quadrant. The fitted trend line is deliberately gone
# too; with the coefficient removed, a regression line would imply a test that
# is not being reported.

figT, axT = plt.subplots(figsize=(7.6, 5.9))
figT.patch.set_facecolor(SURF)
axT.grid(True, color=GRID, lw=0.6, zorder=0)
axT.set_axisbelow(True)
axT.axhline(m_rad, color=MUTED, lw=1.2, ls=':', zorder=2)
axT.axvline(m_icm, color=MUTED, lw=1.2, ls=':', zorder=2)

for mask, col in [(peri, C_PERI), (~peri, C_CENT)]:
    axT.scatter(d.loc[mask, 'icm_dist_um'], d.loc[mask, 'late_radial'],
                s=66, c=col, edgecolors=SURF, linewidths=1.5, alpha=0.9, zorder=3)

xlo, xhi = axT.get_xlim()
ylo, yhi = axT.get_ylim()
yhi += 3
axT.set_ylim(ylo, yhi)
for x, y, n in [((m_icm + xhi) / 2, (m_rad + yhi) / 2, n_pf),
                ((xlo + m_icm) / 2, (m_rad + yhi) / 2, n_pn),
                ((m_icm + xhi) / 2, (ylo + m_rad) / 2, n_cf),
                ((xlo + m_icm) / 2, (ylo + m_rad) / 2, n_cn)]:
    axT.text(x, y, f'{n} cells', ha='center', va='center', fontsize=14,
             color=MUTED, alpha=0.5, zorder=1)

axT.annotate('peripheral', xy=(xlo, m_rad), xytext=(6, 7),
             textcoords='offset points', fontsize=9.5, color=C_PERI)
axT.annotate('central', xy=(xlo, m_rad), xytext=(6, -16),
             textcoords='offset points', fontsize=9.5, color=C_CENT)
axT.annotate('near ICM', xy=(m_icm, ylo), xytext=(-6, 6), ha='right',
             textcoords='offset points', fontsize=9.5, color=MUTED)
axT.annotate('far from ICM', xy=(m_icm, ylo), xytext=(6, 6), ha='left',
             textcoords='offset points', fontsize=9.5, color=MUTED)

axT.set_xlabel('ICM distance at t=30 (µm)  —  where the cell started')
axT.set_ylabel('Mean radial distance from embryo centre, t≥80 (µm)\n— where it ended up')
axT.set_title('Cells that ended up peripheral mostly started far from the ICM',
              fontsize=12.5, color=INK, loc='left', pad=26)
axT.text(0.0, 1.012, f'dataset001 control_2 · {len(d)} tracks · one embryo · '
                     'dotted lines are the medians of each axis',
         transform=axT.transAxes, va='bottom', ha='left', fontsize=9.5, color=MUTED)
for side in ('right', 'top'):
    axT.spines[side].set_visible(False)

figT.text(0.5, -0.02,
          f'{n_pf} of the {n_pf + n_pn} peripheral cells started on the far side of the ICM-distance '
          f'median ({n_pf / (n_pf + n_pn):.0%}), against {n_cf} of {n_cf + n_cn} ({n_cf / (n_cf + n_cn):.0%}) '
          'of the central ones.\n'
          f'PRELIMINARY — one embryo, no statistical test applied. {len(dropped)} further tracks have an '
          'ICM distance but end before t≥80 and are not shown;\nthose are ICM-proximal, so the left of '
          'this axis is under-sampled.',
          ha='center', va='top', fontsize=8.5, color=INK2)

figT.tight_layout()
trend_path = out_dir / f'icm_vs_peripheral_trend_{version}.png'
figT.savefig(trend_path, dpi=200, bbox_inches='tight', facecolor=SURF)
print(f'Saved: {trend_path}')
print(f'  quadrants: peripheral far={n_pf} near={n_pn} | central far={n_cf} near={n_cn}')
